spring.application.name=washq

# Supabase JDBC Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Settings
# 'update' will automatically create/update tables based on your Java @Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Show SQL queries in the console for debugging
spring.jpa.show-sql=true